# Generated by Django 5.0.3 on 2024-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
