# Generated by Django 5.0.3 on 2024-06-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='subject_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
