# Generated by Django 5.0.3 on 2024-06-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='context',
            new_name='text',
        ),
    ]
