# Generated by Django 5.0.3 on 2024-06-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_connect', '0002_connect_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect_answer',
            old_name='Connect',
            new_name='connect',
        ),
    ]
