# Generated by Django 5.0.3 on 2024-05-25 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_register_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, verbose_name='subject code')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('upload', models.FileField(blank=True, null=True, upload_to='C:/Users/kilho/Documents/asyouwrite')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='homework.register')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notice board',
                'verbose_name_plural': 'notice boards',
                'abstract': False,
            },
        ),
    ]
