# Generated by Django 5.0.3 on 2024-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
