# Generated by Django 5.0.3 on 2024-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_submission_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='file_type',
            field=models.CharField(choices=[('all', 'All Documents'), ('pptx', 'PPTX'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('doc', 'DOC'), ('pdf', 'PDF')], default='all', max_length=10),
        ),
    ]
