# Generated by Django 5.0.3 on 2024-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_register_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='file_type',
            field=models.CharField(choices=[('all', 'All Documents'), ('pptx', 'PPTX'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('doc', 'DOC'), ('pdf', 'PDF'), ('hwp', 'HWP')], default='all', max_length=10),
        ),
    ]
