# Generated by Django 5.0.3 on 2024-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secure_entry", "0002_remove_student_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="enrollment_number",
            field=models.CharField(
                max_length=9, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
