# Generated by Django 5.0.3 on 2024-05-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="subject_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subject.subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("subject_code", "day"), name="unique_subject_day"
            ),
        ),
    ]
